---
- name: DATABASE | Install Mariadb server
  package: name=mariadb-server state=present

- name: DATABASE |  Add .my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: DATABASE | Install Mariadb Client
  package: name=mariadb-client state=present

- name: DATABASE | Install Python-Mysql
  package: name=python-mysqldb state=present

# Set root password
# UPDATE mysql.user SET Password=PASSWORD('mysecret') WHERE User='root';
# FLUSH PRIVILEGES;

- name: DATABASE | Set root Password
  mysql_user: login_password={{ root_password }} check_implicit_admin=yes name=root host={{ item }} password={{ root_password }} state=present 
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: DATABASE | Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: DATABASE | Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: DATABASE | Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: DATABASE | Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: DATABASE | Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

# create wordpress database and database user
- name: DATABASE| Creating Wordpress database
  mysql_db: 
        name: wpdb
        state: present

#create wordpress database user and grant all privillages on wpdb database
- name: DATABASE| Creating wpdb database User 
  mysql_user:
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_user_password }}"
        priv: 'wpdb.*:ALL'
        state: present

- name: DATABASE | Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
